# Generated by Django 4.0.6 on 2022-07-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_stuednt_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=20, unique=True)),
                ('ProjectStatus', models.CharField(choices=[('NEW', 'NEW'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=50)),
                ('Department', models.CharField(choices=[('Digital Services', 'Digital Services'), ('Analytics', 'Analytics'), ('Java', 'Java'), ('QA', 'QA'), ('MS Tech', 'MS Tech'), ('BA', 'BA'), ('UI/UX', 'UI/UX')], max_length=50)),
                ('ClientName', models.CharField(max_length=10)),
                ('Technology', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Java', 'Java'), ('.Net', '.Net'), ('Angular', 'Angular'), ('PHP', 'PHP'), ('Tableau', 'Tableau'), ('Power BI', 'Power BI'), ('Selenium', 'Selenium'), ('AWS', 'AWS'), ('Azure', 'Azure'), ('Python', 'Python'), ('Tensorflow', 'Tensorflow')], max_length=50)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('EstimatedHours', models.IntegerField()),
            ],
        ),
    ]
